// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkoWSTdEbfVMO3x8atW-BgDJGfj5wQlWQ',
    appId: '1:745082153922:web:33b22997536347d24b445b',
    messagingSenderId: '745082153922',
    projectId: 'gradproject-ab1be',
    authDomain: 'gradproject-ab1be.firebaseapp.com',
    storageBucket: 'gradproject-ab1be.firebasestorage.app',
    measurementId: 'G-35QN7SR878',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxUkXDJ2IfsroqY9t1QgT0cGZS6cp2GwQ',
    appId: '1:745082153922:android:a67b2e04813ac5554b445b',
    messagingSenderId: '745082153922',
    projectId: 'gradproject-ab1be',
    storageBucket: 'gradproject-ab1be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcbc4JS7feZ1B7hb6DW9tOhtxY7Axzy3o',
    appId: '1:745082153922:ios:c75113e26f934aec4b445b',
    messagingSenderId: '745082153922',
    projectId: 'gradproject-ab1be',
    storageBucket: 'gradproject-ab1be.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcbc4JS7feZ1B7hb6DW9tOhtxY7Axzy3o',
    appId: '1:745082153922:ios:c75113e26f934aec4b445b',
    messagingSenderId: '745082153922',
    projectId: 'gradproject-ab1be',
    storageBucket: 'gradproject-ab1be.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkoWSTdEbfVMO3x8atW-BgDJGfj5wQlWQ',
    appId: '1:745082153922:web:f4f9c62c0f2420c04b445b',
    messagingSenderId: '745082153922',
    projectId: 'gradproject-ab1be',
    authDomain: 'gradproject-ab1be.firebaseapp.com',
    storageBucket: 'gradproject-ab1be.firebasestorage.app',
    measurementId: 'G-HXB3WZVSXB',
  );
}
